# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - docker pull fr3akyphantom/droid-builder:latest 
      - cd $HOME && mkdir twrp
      - cd $HOME/twrp/
      - wget https://storage.googleapis.com/git-repo-downloads/repo
      - chmod +x repo
      - ./repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0
      - ./repo sync
      - cd external
      - git clone https://github.com/TeamWin/external_magisk-prebuilt
      - mv external_magisk-prebuilt magisk-prebuilt
      - cd ..
      - cd device
      - wget http://www.directfilelink.tech/798852306645912/lava.zip
      - unzip lava
      - cd ..
      - pwd
      - |
          docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/builder/twrp/:rw,z" -v "${HOME}/.ccache:/srv/ccache:rw,z" fr3akyphantom/droid-builder bash << EOF
          cd /home/builder/twrp/
          source build/envsetup.sh
          # Choose build flavor as "eng" or "userdebug
          BUILD_FLAVOR="eng"
          lunch omni_LF9810_2GB-eng
          make -j$(nproc --all) recoveryimage
          exit
          EOF
